version: '2'

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@<your_host>:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_ZOOKEEPER_METADATA_MIGRATION_ENABLE=true
    depends_on:
      - zookeeper
    networks:
      - app-tier

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"
      - "9000:9000"
    networks:
      - app-tier

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9002:9002"
    networks:
      - app-tier

  airflow:
    build: .  # Constrói a partir do Dockerfile atual no diretório atual
    depends_on:
      - kafka
      - minio
      - clickhouse
    environment:
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__LOGGING__REMOTE_LOGGING=True
      - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=s3://bronze-layer/logs
      - AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID=my_s3_conn
      - AIRFLOW__SECRETS__BACKEND_CONF={"aws_access_key_id":"minioadmin","aws_secret_access_key":"minioadmin","region_name":"us-east-1","endpoint_url":"http://minio:9000"}
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    networks:
      - app-tier
    command: >
      bash -c "
        airflow db init &&
        (airflow users list | grep -q 'admin' || airflow users create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin) &&
        (airflow connections get my_s3_conn || airflow connections add my_s3_conn  --conn-type aws  --conn-login 'minioadmin'  --conn-password 'minioadmin' --conn-extra '{\"aws_access_key_id\":\"minioadmin\",\"aws_secret_access_key\":\"minioadmin\",\"region_name\":\"us-east-1\",\"endpoint_url\":\"http://minio:9000\"}') &&
        airflow standalone
      "
